/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults, RouterHistory, } from "@stencil/router";
export namespace Components {
    interface AppDashboard {
    }
    interface AppHeroDetail {
        "history": RouterHistory | undefined;
        "match": MatchResults | undefined;
    }
    interface AppHeroSearch {
    }
    interface AppHeroes {
    }
    interface AppMessages {
    }
    interface AppRoot {
    }
}
declare global {
    interface HTMLAppDashboardElement extends Components.AppDashboard, HTMLStencilElement {
    }
    var HTMLAppDashboardElement: {
        prototype: HTMLAppDashboardElement;
        new (): HTMLAppDashboardElement;
    };
    interface HTMLAppHeroDetailElement extends Components.AppHeroDetail, HTMLStencilElement {
    }
    var HTMLAppHeroDetailElement: {
        prototype: HTMLAppHeroDetailElement;
        new (): HTMLAppHeroDetailElement;
    };
    interface HTMLAppHeroSearchElement extends Components.AppHeroSearch, HTMLStencilElement {
    }
    var HTMLAppHeroSearchElement: {
        prototype: HTMLAppHeroSearchElement;
        new (): HTMLAppHeroSearchElement;
    };
    interface HTMLAppHeroesElement extends Components.AppHeroes, HTMLStencilElement {
    }
    var HTMLAppHeroesElement: {
        prototype: HTMLAppHeroesElement;
        new (): HTMLAppHeroesElement;
    };
    interface HTMLAppMessagesElement extends Components.AppMessages, HTMLStencilElement {
    }
    var HTMLAppMessagesElement: {
        prototype: HTMLAppMessagesElement;
        new (): HTMLAppMessagesElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLElementTagNameMap {
        "app-dashboard": HTMLAppDashboardElement;
        "app-hero-detail": HTMLAppHeroDetailElement;
        "app-hero-search": HTMLAppHeroSearchElement;
        "app-heroes": HTMLAppHeroesElement;
        "app-messages": HTMLAppMessagesElement;
        "app-root": HTMLAppRootElement;
    }
}
declare namespace LocalJSX {
    interface AppDashboard {
    }
    interface AppHeroDetail {
        "history"?: RouterHistory | undefined;
        "match"?: MatchResults | undefined;
    }
    interface AppHeroSearch {
    }
    interface AppHeroes {
    }
    interface AppMessages {
    }
    interface AppRoot {
    }
    interface IntrinsicElements {
        "app-dashboard": AppDashboard;
        "app-hero-detail": AppHeroDetail;
        "app-hero-search": AppHeroSearch;
        "app-heroes": AppHeroes;
        "app-messages": AppMessages;
        "app-root": AppRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-dashboard": LocalJSX.AppDashboard & JSXBase.HTMLAttributes<HTMLAppDashboardElement>;
            "app-hero-detail": LocalJSX.AppHeroDetail & JSXBase.HTMLAttributes<HTMLAppHeroDetailElement>;
            "app-hero-search": LocalJSX.AppHeroSearch & JSXBase.HTMLAttributes<HTMLAppHeroSearchElement>;
            "app-heroes": LocalJSX.AppHeroes & JSXBase.HTMLAttributes<HTMLAppHeroesElement>;
            "app-messages": LocalJSX.AppMessages & JSXBase.HTMLAttributes<HTMLAppMessagesElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
        }
    }
}
